import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { FilesystemGamingMediaRepository } from './FilesystemGamingMediaRepository.mjs';
const dirs = [];
afterEach(() => dirs.splice(0).forEach(dir => fs.rmSync(dir, { recursive: true, force: true })));
it('serves content-bank images while retaining party media and rejecting escapes', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gaming-media-')); dirs.push(root);
  const contentGamesDir = path.join(root, 'content'); const partyMediaRoot = path.join(root, 'party');
  fs.mkdirSync(path.join(contentGamesDir, 'charades/images'), { recursive: true }); fs.mkdirSync(partyMediaRoot);
  fs.writeFileSync(path.join(contentGamesDir, 'charades/images/rabbit.svg'), '<svg/>');
  fs.writeFileSync(path.join(partyMediaRoot, 'ready.mp3'), 'audio');
  fs.writeFileSync(path.join(root, 'secret.svg'), 'secret');
  fs.symlinkSync(path.join(root, 'secret.svg'), path.join(contentGamesDir, 'escape.svg'));
  const imageArchiveDir = path.join(root, 'archive'); fs.mkdirSync(imageArchiveDir);
  const hash = crypto.createHash('sha256').update('<svg/>').digest('hex');
  const repo = new FilesystemGamingMediaRepository({ contentGamesDir, partyMediaRoot, imageArchiveDir });
  const image = repo.getPartyMedia(`content/${hash}/charades/images/rabbit.svg`);
  expect(image.kind).toBe('found');
  expect(image.value.resource.mimeType).toBe('image/svg+xml');
  expect(image.value.resource.size).toBe(6);
  fs.mkdirSync(path.join(contentGamesDir, 'directory.svg'));
  expect(repo.getPartyMedia(`content/${hash}/directory.svg`).kind).toBe('not_found');
  fs.writeFileSync(path.join(contentGamesDir, 'choices.yml'), 'secret clues');
  const yamlHash = crypto.createHash('sha256').update('secret clues').digest('hex');
  expect(repo.getPartyMedia(`content/${yamlHash}/choices.yml`).kind).toBe('not_found');
  fs.writeFileSync(path.join(imageArchiveDir, `${hash}.svg`), '<svg/>');
  fs.writeFileSync(path.join(contentGamesDir, 'charades/images/rabbit.svg'), '<svg>changed</svg>');
  expect(repo.getPartyMedia(`content/${hash}/charades/images/rabbit.svg`).value.resource.size).toBe(6);
  fs.unlinkSync(path.join(contentGamesDir, 'charades/images/rabbit.svg'));
  expect(repo.getPartyMedia(`content/${hash}/charades/images/rabbit.svg`).value.resource.size).toBe(6);
  expect(repo.getPartyMedia(`content/${'0'.repeat(64)}/charades/images/rabbit.svg`).kind).toBe('not_found');
  expect(repo.getPartyMedia('ready.mp3').kind).toBe('found');
  const secretHash = crypto.createHash('sha256').update('secret').digest('hex');
  expect(repo.getPartyMedia(`content/${secretHash}/../secret.svg`).kind).toBe('not_found');
  expect(repo.getPartyMedia(`content/${secretHash}/escape.svg`).kind).toBe('not_found');
  expect(repo.getPartyMedia(`content/${secretHash}/missing.svg`).kind).toBe('not_found');
});
