#!/bin/bash

# Function that will be called when script is interrupted
cleanup() {
    kill -- -$$
}

# This traps the Ctrl+C (SIGINT) signal and calls the cleanup function
trap cleanup SIGINT

cd backend && npm start &
cd frontend && npm run dev &
# Wait for all child processes to finish
wait