/**
 * GameShowSessionStore - YAML persistence for game-show sessions.
 *
 * One file per session at <sessionsDir>/<id>.yml. The `state` field is an
 * opaque frontend snapshot (hybrid model: frontend is authoritative during
 * play, this store is the crash/resume checkpoint).
 */
import path from 'path';
import { loadYamlSafe, saveYaml, listYamlFiles, ensureDir } from '#system/utils/index.mjs';

export class GameShowSessionStore {
  constructor({ sessionsDir, logger = console }) {
    this.sessionsDir = sessionsDir;
    this.logger = logger;
    // Guards against two sessions created within the same millisecond
    // colliding on id (ids are timestamp-based). Strictly increasing.
    this._lastTs = 0;
    ensureDir(this.sessionsDir);
  }

  #nextTimestamp() {
    let t = Date.now();
    if (t <= this._lastTs) t = this._lastTs + 1;
    this._lastTs = t;
    return t;
  }

  #file(id) {
    // ids are generated by this class (gs_<digits>) — reject anything else
    if (!/^gs_\d+$/.test(String(id))) return null;
    return path.join(this.sessionsDir, String(id));
  }

  #save(session) {
    saveYaml(this.#file(session.id), session);
    return session;
  }

  create({ game, setId, teams }) {
    const ts = this.#nextTimestamp();
    const iso = new Date(ts).toISOString();
    const session = {
      id: `gs_${ts}`,
      game,
      setId,
      teams: teams || [],
      state: null,
      status: 'active',
      created: iso,
      updated: iso,
    };
    this.logger.info?.('gameshow.session.created', { id: session.id, game, setId });
    return this.#save(session);
  }

  get(id) {
    const file = this.#file(id);
    if (!file) return null;
    return loadYamlSafe(file) || null;
  }

  getActive() {
    // listYamlFiles strips extensions by default (see FileIO.mjs)
    const names = listYamlFiles(this.sessionsDir) || [];
    let newest = null;
    for (const name of names) {
      const s = loadYamlSafe(path.join(this.sessionsDir, name));
      if (s?.status === 'active' && (!newest || s.updated > newest.updated)) newest = s;
    }
    return newest;
  }

  checkpoint(id, state) {
    const session = this.get(id);
    if (!session) return null;
    session.state = state ?? null;
    session.updated = new Date(this.#nextTimestamp()).toISOString();
    return this.#save(session);
  }

  finish(id) {
    const session = this.get(id);
    if (!session) return null;
    session.status = 'complete';
    session.updated = new Date(this.#nextTimestamp()).toISOString();
    this.logger.info?.('gameshow.session.finished', { id });
    return this.#save(session);
  }
}
