#!/usr/bin/env node
// =============================================================================
// gen-config.mjs — generate firmware include/config.h from the household SSOT
// (data/household/screens/kitchen-eink.yml). Keeps Wi-Fi creds + instance values
// OUT of this public repo: the output config.h is gitignored.
//
// Usage:
//   node tools/gen-config.mjs <path-to>/screens/kitchen-eink.yml
//   DAYLIGHT_EINK_CONFIG=<path> node tools/gen-config.mjs
// =============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '..', 'include', 'config.h');

const src = process.argv[2] || process.env.DAYLIGHT_EINK_CONFIG;
if (!src) {
  console.error('ERROR: pass the screen yaml path, or set DAYLIGHT_EINK_CONFIG.');
  process.exit(1);
}

const cfg = yaml.load(readFileSync(src, 'utf8')) || {};
const prov = cfg.provisioning || {};
const backend = cfg.backend || {};

const need = { 'screen': cfg.screen, 'provisioning.wifi_ssid': prov.wifi_ssid,
  'provisioning.wifi_password': prov.wifi_password, 'backend.host': backend.host,
  'backend.port': backend.port };
const missing = Object.entries(need).filter(([, v]) => v === undefined || v === '').map(([k]) => k);
if (missing.length) { console.error(`ERROR: ${src} missing: ${missing.join(', ')}`); process.exit(1); }

const esc = s => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');

// Only the BOOTSTRAP is burned in: Wi-Fi creds + where to reach the server + the
// panel's identity. Everything that might change — rotation, button→action map,
// sleep cadence/schedule — is fetched at runtime (GET /config, X-Eink-Next-Wake
// header) so adjusting it is a SSOT edit + redeploy, never a reflash. The firmware
// carries inert safety fallbacks (main.cpp) for a cold boot with the server down.
const h = `// GENERATED by tools/gen-config.mjs from ${path.basename(src)} — DO NOT COMMIT.
// Bootstrap only. All display/behavior config is fetched at runtime from the
// server (GET /api/v1/eink/config?id=PANEL_ID and the /panel next-wake header).
#pragma once

#define WIFI_SSID        "${esc(prov.wifi_ssid)}"
#define WIFI_PASSWORD    "${esc(prov.wifi_password)}"

#define PANEL_ID         "${esc(cfg.screen)}"
#define DS_HOST          "${esc(backend.host)}"
#define DS_PORT          ${parseInt(backend.port, 10)}
`;

writeFileSync(OUT, h, { mode: 0o600 });
console.log(`[gen-config] ${src}\n[gen-config] -> ${OUT}  (panel=${cfg.screen}, backend=${backend.host}:${backend.port}) — bootstrap only; rotation/buttons/cadence fetched at runtime`);
