#!/usr/bin/env node
// =============================================================================
// gen-config.mjs — generate firmware include/config.h from the household SSOT
// (data/household/screens/kitchen-eink.yml). Keeps Wi-Fi creds + instance values
// OUT of this public repo: the output config.h is gitignored.
//
// Usage:
//   node tools/gen-config.mjs <path-to>/screens/kitchen-eink.yml
//   DAYLIGHT_EINK_CONFIG=<path> node tools/gen-config.mjs
// =============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '..', 'include', 'config.h');

const src = process.argv[2] || process.env.DAYLIGHT_EINK_CONFIG;
if (!src) {
  console.error('ERROR: pass the screen yaml path, or set DAYLIGHT_EINK_CONFIG.');
  process.exit(1);
}

const cfg = yaml.load(readFileSync(src, 'utf8')) || {};
const prov = cfg.provisioning || {};
const backend = cfg.backend || {};
const buttons = cfg.buttons || {};
const display = (cfg.hardware && cfg.hardware.display) || {};

const need = { 'screen': cfg.screen, 'provisioning.wifi_ssid': prov.wifi_ssid,
  'provisioning.wifi_password': prov.wifi_password, 'backend.host': backend.host,
  'backend.port': backend.port };
const missing = Object.entries(need).filter(([, v]) => v === undefined || v === '').map(([k]) => k);
if (missing.length) { console.error(`ERROR: ${src} missing: ${missing.join(', ')}`); process.exit(1); }

// "30min" / "1h" / "15m" -> minutes
function minutes(v, dflt = 30) {
  if (!v) return dflt;
  const m = String(v).match(/^(\d+)\s*(h|hr|hour|m|min|minute)?/i);
  if (!m) return dflt;
  const n = parseInt(m[1], 10);
  return /^h/i.test(m[2] || 'm') ? n * 60 : n;
}
const esc = s => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const h = `// GENERATED by tools/gen-config.mjs from ${path.basename(src)} — DO NOT COMMIT.
#pragma once

#define WIFI_SSID        "${esc(prov.wifi_ssid)}"
#define WIFI_PASSWORD    "${esc(prov.wifi_password)}"

#define PANEL_ID         "${esc(cfg.screen)}"
#define DS_HOST          "${esc(backend.host)}"
#define DS_PORT          ${parseInt(backend.port, 10)}

#define DISPLAY_ROTATION ${parseInt(display.rotation ?? 0, 10)}
#define SLEEP_MINUTES    ${minutes(cfg.refresh && cfg.refresh.interval)}

// Button GPIOs are hardware-class (E1003); action strings come from the SSOT.
#define BTN_GREEN_GPIO   3
#define BTN_GREEN_ACTION "${esc(buttons.green || 'select')}"
#define BTN_RIGHT_GPIO   4
#define BTN_RIGHT_ACTION "${esc(buttons.right || 'next')}"
#define BTN_LEFT_GPIO    5
#define BTN_LEFT_ACTION  "${esc(buttons.left || 'prev')}"
`;

writeFileSync(OUT, h, { mode: 0o600 });
console.log(`[gen-config] ${src}\n[gen-config] -> ${OUT}  (panel=${cfg.screen}, backend=${backend.host}:${backend.port}, sleep=${minutes(cfg.refresh && cfg.refresh.interval)}m, rot=${display.rotation ?? 0})`);
