/**
 * Shopping Lifelog Extractor
 *
 * Extracts shopping/purchase data from shopping.yml (generated by shopping harvester)
 * Structure: Array of receipts with date, merchant, items, and totals
 *
 * @module journalist/extractors
 */

import { ILifelogExtractor, ExtractorCategory } from './ILifelogExtractor.mjs';

/**
 * Shopping/purchase data extractor
 * @implements {ILifelogExtractor}
 */
export class ShoppingExtractor extends ILifelogExtractor {
  get source() {
    return 'shopping';
  }

  get category() {
    return ExtractorCategory.FINANCE;
  }

  get filename() {
    return 'shopping';
  }

  /**
   * Extract shopping data for a specific date
   * @param {Object} data - Full shopping.yml data
   * @param {string} date - Target date 'YYYY-MM-DD'
   * @returns {Object|null} Extracted data or null
   */
  extractForDate(data, date) {
    const receipts = data?.receipts || [];
    const dayReceipts = receipts.filter((r) => r.date === date);

    if (dayReceipts.length === 0) return null;

    const totalSpent = dayReceipts.reduce((sum, r) => sum + (r.total || 0), 0);
    const totalItems = dayReceipts.reduce(
      (sum, r) => sum + (r.items?.length || 0),
      0
    );

    return {
      receipts: dayReceipts.map((r) => ({
        merchant: r.merchant,
        orderId: r.order_id,
        total: r.total,
        itemCount: r.items?.length || 0,
        items: r.items?.map((i) => i.name) || [],
      })),
      totalSpent,
      totalItems,
      merchantCount: new Set(dayReceipts.map((r) => r.merchant)).size,
    };
  }

  /**
   * Format extracted data as human-readable summary
   * @param {Object} entry - Extracted data
   * @returns {string|null} Formatted summary or null
   */
  summarize(entry) {
    if (!entry || entry.receipts.length === 0) return null;

    const lines = ['SHOPPING:'];

    // Summary line
    const merchantText =
      entry.merchantCount === 1
        ? entry.receipts[0].merchant
        : `${entry.merchantCount} retailers`;
    lines.push(
      `  ${entry.receipts.length} order${entry.receipts.length > 1 ? 's' : ''} from ${merchantText}`
    );

    if (entry.totalSpent > 0) {
      lines.push(`  Total spent: $${entry.totalSpent.toFixed(2)}`);
    }

    if (entry.totalItems > 0) {
      lines.push(
        `  ${entry.totalItems} item${entry.totalItems > 1 ? 's' : ''} purchased`
      );
    }

    // Detail each order
    entry.receipts.forEach((receipt) => {
      const total = receipt.total
        ? `$${receipt.total.toFixed(2)}`
        : 'unknown total';
      lines.push(
        `  - ${receipt.merchant}: ${total} (${receipt.itemCount} item${receipt.itemCount !== 1 ? 's' : ''})`
      );

      // Show first 3 items
      if (receipt.items.length > 0) {
        const itemsToShow = receipt.items.slice(0, 3);
        itemsToShow.forEach((item) => {
          const truncated =
            item.length > 60 ? item.substring(0, 57) + '...' : item;
          lines.push(`    - ${truncated}`);
        });
        if (receipt.items.length > 3) {
          lines.push(`    - ...and ${receipt.items.length - 3} more`);
        }
      }
    });

    return lines.join('\n');
  }
}

// Export singleton instance for backward compatibility
export const shoppingExtractor = new ShoppingExtractor();

export default ShoppingExtractor;
