#!/usr/bin/env node
// =============================================================================
// gen-config.mjs — generate firmware include/config.h from the household SSOT
// (data/household/config/barcode-relay.yml). Keeps Wi-Fi creds + instance values
// OUT of this public repo: the output config.h is gitignored.
//
// Usage:
//   node tools/gen-config.mjs <path-to>/config/barcode-relay.yml [relay-id]
//   DAYLIGHT_BARCODE_CONFIG=<path> node tools/gen-config.mjs [relay-id]
// =============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '..', 'include', 'config.h');

const src = process.argv[2] || process.env.DAYLIGHT_BARCODE_CONFIG;
if (!src) {
  console.error('ERROR: pass the barcode-relay yaml path, or set DAYLIGHT_BARCODE_CONFIG.');
  process.exit(1);
}

const cfg = yaml.load(readFileSync(src, 'utf8')) || {};
const prov = cfg.provisioning || {};
const backend = cfg.backend || {};
const relays = cfg.relays || {};

const wantId = process.argv[3] || Object.keys(relays)[0];
const relay = relays[wantId];
if (!relay) {
  console.error(`ERROR: relay id "${wantId}" not found. Available: ${Object.keys(relays).join(', ') || '(none)'}`);
  process.exit(1);
}
const scanner = relay.scanner || {};
const nutri = relay.nutribot || {};
const route = relay.route || 'content';

// ws_path + scanner identity are optional (sensible defaults); the rest are required.
const wsPath = backend.ws_path || '/ws';
const scannerMac = scanner.mac || '';
const scannerName = scanner.name || 'DS2278';

const need = {
  'provisioning.wifi_ssid': prov.wifi_ssid,
  'provisioning.wifi_password': prov.wifi_password,
  'backend.host': backend.host,
  'backend.port': backend.port,
  [`relays.${wantId}.route`]: route,
  [`relays.${wantId}.scanner.mac`]: scannerMac,
  [`relays.${wantId}.scanner.name`]: scannerName,
};
if (route === 'nutribot') {
  need[`relays.${wantId}.nutribot.user_id`] = nutri.user_id;
}
const missing = Object.entries(need).filter(([, v]) => v === undefined || v === '').map(([k]) => k);
if (missing.length) { console.error(`ERROR: ${src} missing: ${missing.join(', ')}`); process.exit(1); }

const esc = s => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const h = `// GENERATED by tools/gen-config.mjs from ${path.basename(src)} (relay: ${wantId}) — DO NOT COMMIT.
// Bootstrap only: Wi-Fi + backend event-bus WebSocket + DS2278 BLE identity.
// Use the stable hostname (not an IP) so the relay survives a server address change.
#pragma once

#define WIFI_SSID        "${esc(prov.wifi_ssid)}"
#define WIFI_PASSWORD    "${esc(prov.wifi_password)}"

#define WS_HOST          "${esc(backend.host)}"
#define WS_PORT          ${parseInt(backend.port, 10)}
#define WS_PATH          "${esc(wsPath)}"

#define RELAY_ID         "${esc(wantId)}"
#define RELAY_LABEL      "${esc(relay.label || wantId)}"
#define RELAY_ROUTE      "${esc(route)}"
#define NUTRIBOT_USER_ID "${esc(nutri.user_id || '')}"
#define NUTRIBOT_CONVERSATION_ID "${esc(nutri.conversation_id || '')}"

#define SCANNER_MAC      "${esc(scannerMac)}"
#define SCANNER_NAME     "${esc(scannerName)}"
`;

writeFileSync(OUT, h, { mode: 0o600 });
console.log(`[gen-config] ${src} (relay=${wantId})`);
console.log(`[gen-config] -> ${OUT}  (ws=${backend.host}:${backend.port}${wsPath}, scanner=${scannerName}, route=${route})`);
