#!/usr/bin/env node
// =============================================================================
// gen-config.mjs — generate firmware include/config.h from the household SSOT
// (data/household/config/scantrons.yml). Keeps Wi-Fi creds + instance values OUT
// of the repo: the output config.h is gitignored.
//
// Usage:
//   node tools/gen-config.mjs <path-to>/config/scantrons.yml [reader-id]
//   DAYLIGHT_SCANTRONS_CONFIG=<path> node tools/gen-config.mjs [reader-id]
//
// reader-id defaults to the first key under `scanners:`.
// =============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '..', 'include', 'config.h');

const src = process.argv[2] || process.env.DAYLIGHT_SCANTRONS_CONFIG;
if (!src) {
  console.error('ERROR: pass scantrons.yml path, or set DAYLIGHT_SCANTRONS_CONFIG.');
  process.exit(1);
}

const cfg = yaml.load(readFileSync(src, 'utf8')) || {};
const prov = cfg.provisioning || {};
const backend = cfg.backend || {};
const scanners = cfg.scanners || {};

const wantId = process.argv[3] || Object.keys(scanners)[0];
const sc = scanners[wantId];
if (!sc) {
  console.error(`ERROR: reader id "${wantId}" not found. Available: ${Object.keys(scanners).join(', ') || '(none)'}`);
  process.exit(1);
}
const serial = sc.serial || {};

const need = {
  'provisioning.wifi_ssid': prov.wifi_ssid,
  'provisioning.wifi_password': prov.wifi_password,
  'backend.host': backend.host,
  'backend.port': backend.port,
};
const missing = Object.entries(need).filter(([, v]) => v === undefined || v === '').map(([k]) => k);
if (missing.length) { console.error(`ERROR: ${src} missing: ${missing.join(', ')}`); process.exit(1); }

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');

// Map YAML framing (e.g. "8N1", "7E1") to the Arduino SERIAL_* constant.
const framing = String(serial.framing || '8N1').toUpperCase();
const FRAMING_MAP = {
  '8N1': 'SERIAL_8N1', '8E1': 'SERIAL_8E1', '8O1': 'SERIAL_8O1',
  '7N1': 'SERIAL_7N1', '7E1': 'SERIAL_7E1', '7O1': 'SERIAL_7O1',
};
const uartConfig = FRAMING_MAP[framing];
if (!uartConfig) { console.error(`ERROR: unknown serial.framing "${framing}"`); process.exit(1); }

const h = `// GENERATED by tools/gen-config.mjs from ${path.basename(src)} (reader: ${wantId}) — DO NOT COMMIT.
#pragma once

#define WIFI_SSID      "${esc(prov.wifi_ssid)}"
#define WIFI_PASSWORD  "${esc(prov.wifi_password)}"

#define BACKEND_HOST   "${esc(backend.host)}"
#define BACKEND_PORT   ${parseInt(backend.port, 10)}
#define WS_PATH        "${esc(backend.ws_path || '/ws')}"

#define READER_ID      "${esc(wantId)}"
#define BUS_TOPIC      "${esc(sc.topic || 'scantron')}"

#define UART_RX_PIN    ${parseInt(serial.rx_pin ?? 5, 10)}
#define UART_TX_PIN    ${parseInt(serial.tx_pin ?? 6, 10)}
#define UART_BAUD      ${parseInt(serial.baud ?? 9600, 10)}
#define UART_CONFIG    ${uartConfig}
#define SNIFF_MODE     ${sc.sniff_mode === false ? 0 : 1}
`;

writeFileSync(OUT, h, { mode: 0o600 });
console.log(`[gen-config] ${src} (reader=${wantId})\n[gen-config] -> ${OUT}  backend=${backend.host}:${backend.port}${backend.ws_path || '/ws'}  ${serial.baud ?? 9600}/${framing} sniff=${sc.sniff_mode === false ? 0 : 1}`);
