# Dockerfile
FROM alseambusher/crontab-ui

RUN apk update && \
    apk add curl && \
    curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
    chmod a+rx /usr/local/bin/yt-dlp