/**
 * Nutrition Lifelog Extractor
 * 
 * Extracts nutrition data from nutriday.yml (generated by NutriBot)
 * Structure: Date-keyed object with daily calorie and macro summaries
 */

export const nutritionExtractor = {
  source: 'nutrition',
  category: 'health',
  filename: 'nutriday',
  
  /**
   * Extract nutrition data for a specific date
   * @param {Object} data - Full nutriday.yml data
   * @param {string} date - Target date 'YYYY-MM-DD'
   * @returns {Object|null} Extracted data or null
   */
  extractForDate(data, date) {
    const day = data?.[date];
    if (!day) return null;
    return {
      calories: day.calories || 0,
      protein: day.protein || 0,
      carbs: day.carbs || 0,
      fat: day.fat || 0,
      fiber: day.fiber || 0,
      sodium: day.sodium || 0,
      sugar: day.sugar || 0,
      cholesterol: day.cholesterol || 0,
      foodItems: day.food_items || []
    };
  },

  /**
   * Format extracted data as human-readable summary
   * @param {Object} entry - Extracted data
   * @returns {string|null} Formatted summary or null
   */
  summarize(entry) {
    if (!entry || entry.calories === 0) return null;
    
    const lines = [
      'NUTRITION:',
      `  Total calories: ${entry.calories} kcal`,
      `  Macros: ${entry.protein}g protein, ${entry.carbs}g carbs, ${entry.fat}g fat`
    ];
    
    if (entry.fiber > 0) lines.push(`  Fiber: ${entry.fiber}g`);
    if (entry.sodium > 0) lines.push(`  Sodium: ${entry.sodium}mg`);
    
    // Add food items if available (limit to top 5 by calories)
    if (entry.foodItems && entry.foodItems.length > 0) {
      lines.push('  Foods consumed:');
      const topItems = entry.foodItems.slice(0, 5);
      topItems.forEach(item => {
        lines.push(`    - ${item}`);
      });
      if (entry.foodItems.length > 5) {
        lines.push(`    ... and ${entry.foodItems.length - 5} more items`);
      }
    }
    
    return lines.join('\n');
  }
};

export default nutritionExtractor;
