// scantron-relay firmware — M5Stack ATOM Lite (ESP32-PICO-D4).
//
// Taps the RS-232 serial output of a Chatsworth Data OMR 1200 (via an M5 ATOMIC
// RS232 base / MAX3232) and forwards it over WebSocket to the DaylightStation
// event bus (/ws). The backend re-broadcasts the `scantron` topic.
//
// This starts life as a SERIAL SNIFFER: with SNIFF_MODE=1 it forwards every
// received byte to the bus as a hex-encoded {"type":"raw"} message so the real
// OMR 1200 frame format can be captured from actual scanned sheets. Once the
// framing is known, add a decoder in handleFrame() and flip SNIFF_MODE off.
//
// Requires include/config.h (generated by tools/gen-config.mjs; gitignored).

#include <Arduino.h>
#include <WiFi.h>
#include <WebSocketsClient.h>
#include <ArduinoJson.h>
#include <FastLED.h>
#include "config.h"

// Onboard SK6812 status LED. GPIO27 on ATOM Lite.
#define LED_PIN   27
#define NUM_LEDS  1
static CRGB leds[NUM_LEDS];

static WebSocketsClient ws;
static bool wsConnected = false;

// Serial2 = the RS-232 tap. Native USB CDC (Serial) stays free for the monitor.
#define OMR Serial2

static void setLed(const CRGB &c) { leds[0] = c; FastLED.show(); }

static void onWsEvent(WStype_t type, uint8_t *payload, size_t len) {
  switch (type) {
    case WStype_CONNECTED:
      wsConnected = true;
      setLed(CRGB::Green);
      break;
    case WStype_DISCONNECTED:
      wsConnected = false;
      setLed(CRGB::Amber);
      break;
    default:
      break;
  }
}

// Ship one message to the event bus. Caller supplies a fully-built JSON doc.
static void emit(JsonDocument &doc) {
  if (!wsConnected) return;
  String out;
  serializeJson(doc, out);
  ws.sendTXT(out);
}

// --- protocol discovery: forward raw bytes hex-encoded, batched by idle gap ---
static void emitRaw(const uint8_t *buf, size_t n) {
  JsonDocument doc;
  doc["source"] = "scantron-relay";
  doc["type"]   = "raw";
  doc["id"]     = READER_ID;
  char hex[3];
  String s;
  for (size_t i = 0; i < n; i++) { sprintf(hex, "%02X", buf[i]); s += hex; }
  doc["hex"] = s;
  doc["len"] = (uint16_t)n;
  emit(doc);
}

// --- TODO(protocol captured): decode a real OMR 1200 sheet frame here ---
// static void handleFrame(const uint8_t *buf, size_t n) {
//   JsonDocument doc;
//   doc["source"]  = "scantron-relay";
//   doc["type"]    = "sheet";
//   doc["id"]      = READER_ID;
//   // JsonArray answers = doc["answers"].to<JsonArray>();
//   // ... fill from decoded bytes ...
//   emit(doc);
// }

static void connectWifi() {
  setLed(CRGB::Red);
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) { delay(250); }
  setLed(CRGB::Blue);
}

void setup() {
  Serial.begin(115200);
  FastLED.addLeds<SK6812, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(40);

  // RS-232 tap. UART_CONFIG/UART_BAUD are placeholders until sniffed.
  OMR.begin(UART_BAUD, UART_CONFIG, UART_RX_PIN, UART_TX_PIN);

  connectWifi();

  ws.begin(BACKEND_HOST, BACKEND_PORT, WS_PATH);
  ws.onEvent(onWsEvent);
  ws.setReconnectInterval(3000);
}

// Accumulate bytes; flush on an inter-byte idle gap (a crude frame boundary
// that works for record-oriented serial output). Tune FRAME_IDLE_MS after
// observing real timing.
static const uint32_t FRAME_IDLE_MS = 30;
static uint8_t frameBuf[512];
static size_t  frameLen = 0;
static uint32_t lastByteMs = 0;

void loop() {
  ws.loop();

  while (OMR.available()) {
    int b = OMR.read();
    if (b < 0) break;
    if (frameLen < sizeof(frameBuf)) frameBuf[frameLen++] = (uint8_t)b;
    lastByteMs = millis();
    setLed(CRGB::Purple);   // brief flash: bytes flowing
  }

  if (frameLen > 0 && (millis() - lastByteMs) > FRAME_IDLE_MS) {
#if SNIFF_MODE
    emitRaw(frameBuf, frameLen);
#else
    // handleFrame(frameBuf, frameLen);
#endif
    frameLen = 0;
    setLed(wsConnected ? CRGB::Green : CRGB::Amber);
  }
}
