#!/usr/bin/env node
// =============================================================================
// gen-config.mjs — generate firmware include/config.h from the household SSOT
// (data/household/config/scales.yml). Keeps Wi-Fi creds + instance values OUT of
// the repo: the output config.h is gitignored.
//
// Usage:
//   node tools/gen-config.mjs <path-to>/config/scales.yml [scale-id]
//   DAYLIGHT_SCALES_CONFIG=<path> node tools/gen-config.mjs [scale-id]
//
// scale-id defaults to the first key under `scales:`.
// =============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Output path is overridable. It was added so the retired DS6878 board could
// reuse this generator while keeping its own generated config.h; it stays
// because a second scale (another ATOM, another key under `scales:`) needs the
// same escape hatch.
const OUT = process.env.DAYLIGHT_CONFIG_OUT
  || path.join(__dirname, '..', 'include', 'config.h');

const src = process.argv[2] || process.env.DAYLIGHT_SCALES_CONFIG;
if (!src) {
  console.error('ERROR: pass scales.yml path, or set DAYLIGHT_SCALES_CONFIG.');
  process.exit(1);
}

const cfg = yaml.load(readFileSync(src, 'utf8')) || {};
const prov = cfg.provisioning || {};
const backend = cfg.backend || {};
const scales = cfg.scales || {};

const wantId = process.argv[3] || Object.keys(scales)[0];
const scale = scales[wantId];
if (!scale) {
  console.error(`ERROR: scale id "${wantId}" not found. Available: ${Object.keys(scales).join(', ') || '(none)'}`);
  process.exit(1);
}
const ble = scale.ble || {};
const barcode = scale.barcode || {};
const decode = ble.decode || {};
const emit = scale.emit || {};

// A device may carry a scale, a barcode scanner, or both. BOTH IS THE NORMAL
// CASE and is what `kitchen-food-scale` is: a BLE scale plus a DS2278 BLE HID
// scanner, two LE connections sharing the LE scheduler.
//
// This used to warn that both-on-one-board would drop the scanner with HCI 0x08.
// That was true of the Classic-BT DS6878 and only of it — Classic paging cannot
// survive a concurrent BLE scan on this single radio. The DS2278 is LE, so the
// warning fired on the one configuration we now want. Omit `ble:` for a
// scanner-only board, omit `barcode:` for a scale-only board; both is fine.
const scaleEnabled = Boolean(ble.match_name);
const barcodeEnabled = Boolean(barcode.mac || barcode.name);
if (!scaleEnabled && !barcodeEnabled) {
  console.error(`ERROR: "${wantId}" has neither a scale (ble.match_name) nor a scanner (barcode.mac/name).`);
  process.exit(1);
}
// Adopt-by-name is a bring-up affordance, not a resting state: any BLE HID
// keyboard that advertises near the kitchen can be claimed, and the firmware then
// locks onto it. Say so at generate time, which is the last moment before the
// value is baked into a binary.
if (barcodeEnabled && !barcode.mac) {
  console.warn(`[gen-config] NOTE: "${wantId}" has no barcode.mac — adopting the first BLE HID device`);
  console.warn(`[gen-config]       matching name "${barcode.name || 'DS2278'}". Pin the LE address once known.`);
}

const need = {
  'provisioning.wifi_ssid': prov.wifi_ssid,
  'provisioning.wifi_password': prov.wifi_password,
  'backend.host': backend.host,
  'backend.port': backend.port,
  ...(scaleEnabled ? {
    [`scales.${wantId}.ble.service_uuid`]: ble.service_uuid,
    [`scales.${wantId}.ble.notify_char`]: ble.notify_char,
  } : {}),
};
const missing = Object.entries(need).filter(([, v]) => v === undefined || v === '').map(([k]) => k);
if (missing.length) { console.error(`ERROR: ${src} missing: ${missing.join(', ')}`); process.exit(1); }

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const hz = Number(emit.heartbeat_hz) > 0 ? Number(emit.heartbeat_hz) : 0.5;
const heartbeatMs = Math.round(1000 / hz);
const divisor = Number(decode.divisor) > 0 ? Number(decode.divisor) : 1;

const h = `// GENERATED by tools/gen-config.mjs from ${path.basename(src)} (scale: ${wantId}) — DO NOT COMMIT.
#pragma once

#define WIFI_SSID          "${esc(prov.wifi_ssid)}"
#define WIFI_PASSWORD      "${esc(prov.wifi_password)}"

#define WS_HOST            "${esc(backend.host)}"
#define WS_PORT            ${parseInt(backend.port, 10)}
#define WS_PATH            "${esc(backend.ws_path || '/ws')}"

// 0 = scanner-only board: BLE scale discovery never starts. The BLE stack still
// initialises — only the scan is suppressed. This was the flag that made the
// DS6878 board possible at all (no scan, so nothing to starve its Classic link);
// with both peripherals on LE it is now just "this board has no scale".
#define SCALE_ENABLED      ${scaleEnabled ? 1 : 0}
#define SCALE_ID           "${esc(wantId)}"
#define SCALE_MATCH_NAME   "${esc(ble.match_name || '')}"
#define SCALE_SERVICE_UUID "${esc(ble.service_uuid || '0000ffb0-0000-1000-8000-00805f9b34fb')}"
#define SCALE_NOTIFY_UUID  "${esc(ble.notify_char || '0000ffb2-0000-1000-8000-00805f9b34fb')}"

#define WEIGHT_OFFSET      ${parseInt(decode.weight_offset ?? 2, 10)}
#define WEIGHT_DIVISOR     ${divisor}
#define STABLE_BYTE        ${parseInt(decode.stable_byte ?? 6, 10)}
#define STABLE_VALUE       ${decode.stable_value != null ? `0x${Number(decode.stable_value).toString(16).toUpperCase()}` : '0xAA'}
#define UNIT_BYTE          ${parseInt(decode.unit_byte ?? 8, 10)}

#define EMIT_MIN_DELTA_G   ${parseInt(emit.min_delta_g ?? 1, 10)}
#define HEARTBEAT_MS       ${heartbeatMs}

#define BARCODE_ENABLED    ${barcodeEnabled ? 1 : 0}
#define BARCODE_ID         "${esc(barcode.id || 'content-barcode')}"
#define BARCODE_ROUTE      "${esc(barcode.route || 'content')}"
// A set MAC is AUTHORITATIVE in the scan callback — it is the whole match, not
// one clause of an OR. Empty = adopt the first BLE HID device whose advertised
// name contains BARCODE_NAME (bring-up only; see the note printed above).
#define BARCODE_MAC        "${esc(barcode.mac || '')}"
#define BARCODE_NAME       "${esc(barcode.name || 'DS2278')}"
`;
// BARCODE_HOST_NAME / BARCODE_PASSIVE / BARCODE_FIXED_PASSKEY are NOT emitted any
// more. All three were Classic-BT pairing knobs for the DS6878 (host name shown
// while pairing, page-vs-wait, and the fixed SSP passkey for KeyboardOnly io-cap).
// NimBLE has no Classic support, nothing in main.cpp reads them, and a BLE HID
// bond is Just Works with io-cap NONE — there is no passkey to pre-stage.

writeFileSync(OUT, h, { mode: 0o600 });
console.log(`[gen-config] ${src} (scale=${wantId})\n[gen-config] -> ${OUT}  backend=${backend.host}:${backend.port}${backend.ws_path || '/ws'}`);
