#!/usr/bin/env node
// =============================================================================
// gen-config.mjs — generate firmware include/config.h from the household SSOT
// (data/household/config/vehicles.yml). Keeps Wi-Fi creds + instance values OUT
// of the repo: the output config.h is gitignored.
//
// Usage:
//   node tools/gen-config.mjs <path-to>/config/vehicles.yml [vehicle-id]
//   DAYLIGHT_VEHICLES_CONFIG=<path> node tools/gen-config.mjs [vehicle-id]
//
// vehicle-id defaults to the first key under `vehicles:`.
// =============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '..', 'include', 'config.h');

const src = process.argv[2] || process.env.DAYLIGHT_VEHICLES_CONFIG;
if (!src) {
  console.error('ERROR: pass vehicles.yml path, or set DAYLIGHT_VEHICLES_CONFIG.');
  process.exit(1);
}

const cfg = yaml.load(readFileSync(src, 'utf8')) || {};
const prov = cfg.provisioning || {};
const backend = cfg.backend || {};
const vehicles = cfg.vehicles || {};

const wantId = process.argv[3] || Object.keys(vehicles)[0];
const vehicle = vehicles[wantId];
if (!vehicle) {
  console.error(`ERROR: vehicle id "${wantId}" not found. Available: ${Object.keys(vehicles).join(', ') || '(none)'}`);
  process.exit(1);
}
const sampling = vehicle.sampling || {};
const emit = vehicle.emit || {};

const need = {
  'provisioning.wifi_ssid': prov.wifi_ssid,
  'provisioning.wifi_password': prov.wifi_password,
  'backend.host': backend.host,
  'backend.port': backend.port,
};
const missing = Object.entries(need).filter(([, v]) => v === undefined || v === '').map(([k]) => k);
if (missing.length) { console.error(`ERROR: ${src} missing: ${missing.join(', ')}`); process.exit(1); }

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const num = (v, dflt) => (Number(v) > 0 ? Number(v) : dflt);

const h = `// GENERATED by tools/gen-config.mjs from ${path.basename(src)} (vehicle: ${wantId}) — DO NOT COMMIT.
#pragma once

#define WIFI_SSID           "${esc(prov.wifi_ssid)}"
#define WIFI_PASSWORD       "${esc(prov.wifi_password)}"

#define WS_HOST             "${esc(backend.host)}"
#define WS_PORT             ${parseInt(backend.port, 10)}
#define WS_PATH             "${esc(backend.ws_path || '/ws')}"

#define VEHICLE_ID          "${esc(wantId)}"

#define SAMPLE_HZ           ${num(sampling.hz, 1)}
#define SNAPSHOT_S          ${num(emit.snapshot_s, 15)}
#define TRIP_CHUNK_SAMPLES  ${num(emit.trip_chunk_samples, 300)}
`;

writeFileSync(OUT, h, { mode: 0o600 });
console.log(`[gen-config] ${src} (vehicle=${wantId})\n[gen-config] -> ${OUT}  backend=${backend.host}:${backend.port}${backend.ws_path || '/ws'}`);
