import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { generateMathAssets, renderMathAsset, validateMathAssetSpec } from './math-assets.mjs';

const roots = [];
const spec = (over = {}) => ({
  schema: 'school.math-svg/v1', ref: 'school/math/proof/number-line', kind: 'number_line',
  alt: 'A number line from zero to ten.', params: { min: 0, max: 10, step: 1, marks: [{ value: 6, label: 'A' }] }, ...over,
});

afterEach(() => roots.splice(0).forEach((root) => fs.rmSync(root, { recursive: true, force: true })));

describe('math asset authoring', () => {
  it('renders deterministic, self-contained monochrome SVG', () => {
    const first = renderMathAsset(spec()); const second = renderMathAsset(spec());
    expect(first).toBe(second);
    expect(first).toContain('viewBox="0 0 540 130"');
    expect(first).toContain('<title id="title">A number line from zero to ten.</title>');
    expect(first).not.toMatch(/(?:<script|\s(?:href|xlink:href)=|url\()/u);
  });

  it.each(['ten_frame', 'counters', 'base_ten', 'array', 'fraction_model', 'clock', 'data_graph', 'shape_set'])(
    'renders the %s primitive', (kind) => {
      const params = {
        ten_frame: { filled: 7 }, counters: { count: 8, columns: 4 }, base_ten: { hundreds: 1, tens: 2, ones: 3 },
        array: { rows: 3, columns: 4 }, fraction_model: { numerator: 2, denominator: 5 }, clock: { hour: 3, minute: 30 },
        data_graph: { labels: ['A', 'B'], values: [2, 4] }, shape_set: { shapes: [{ label: 'A', type: 'triangle' }, { label: 'B', type: 'square' }] },
      }[kind];
      expect(renderMathAsset(spec({ ref: `school/math/proof/${kind.replaceAll('_', '-')}`, kind, params }))).toContain('<svg');
    },
  );

  it('rejects traversal and unknown primitives', () => {
    expect(validateMathAssetSpec(spec({ ref: 'school/math/../secret', kind: 'plot' }))).toEqual(expect.arrayContaining([
      expect.stringMatching(/ref/), expect.stringMatching(/kind/),
    ]));
  });

  it('writes and then checks the exact generated bytes', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'math-assets-')); roots.push(root);
    const source = path.join(root, 'number-line.yml');
    fs.writeFileSync(source, [
      'schema: school.math-svg/v1', 'ref: school/math/proof/number-line', 'kind: number_line',
      'alt: A number line.', 'params: { min: 0, max: 5, step: 1 }', '',
    ].join('\n'));
    const [created] = generateMathAssets({ target: source, dataDir: root });
    expect(fs.existsSync(created.output)).toBe(true);
    expect(() => generateMathAssets({ target: source, dataDir: root, check: true })).not.toThrow();
  });
});
