#!/usr/bin/env node
/**
 * Generate the framebuffer include used by the TI-86 QR display experiment.
 *
 * Usage: node _extensions/ti86-app/tools/generate-demo.mjs [--score 0..5]
 *
 * QR Version 1/M is fixed deliberately: 21 modules, doubled to 42×42 pixels.
 * With a four-module quiet zone it consumes 58×58 pixels, safely inside the
 * TI-86's 128×64 monochrome LCD.  The payload stays tiny so it will remain
 * Version 1 as the eventual result envelope replaces this demo value.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import QRCode from 'qrcode';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const scoreArg = process.argv.indexOf('--score');
const score = scoreArg === -1 ? 5 : Number(process.argv[scoreArg + 1]);

if (!Number.isInteger(score) || score < 0 || score > 5) {
  console.error('Usage: generate-demo.mjs [--score 0..5]');
  process.exit(1);
}

const payload = `DS1:DEMO:${score}`;
const qr = QRCode.create(payload, { version: 1, errorCorrectionLevel: 'M' });
if (qr.modules.size !== 21) {
  throw new Error(`Expected Version-1 QR (21 modules), got ${qr.modules.size}`);
}

const WIDTH = 128;
const HEIGHT = 64;
const BYTES_PER_ROW = WIDTH / 8;
const SCALE = 2;
const QUIET = 4 * SCALE;
const qrPixels = qr.modules.size * SCALE;
const originX = Math.floor((WIDTH - (qrPixels + 2 * QUIET)) / 2) + QUIET;
const originY = Math.floor((HEIGHT - (qrPixels + 2 * QUIET)) / 2) + QUIET;
const frame = new Uint8Array(BYTES_PER_ROW * HEIGHT);

function setPixel(x, y) {
  const offset = y * BYTES_PER_ROW + Math.floor(x / 8);
  frame[offset] |= 0x80 >> (x & 7);
}

for (let row = 0; row < qr.modules.size; row += 1) {
  for (let col = 0; col < qr.modules.size; col += 1) {
    if (!qr.modules.get(row, col)) continue;
    for (let dy = 0; dy < SCALE; dy += 1) {
      for (let dx = 0; dx < SCALE; dx += 1) {
        setPixel(originX + col * SCALE + dx, originY + row * SCALE + dy);
      }
    }
  }
}

const hex = (value) => `$${value.toString(16).padStart(2, '0').toUpperCase()}`;
const rows = [];
for (let offset = 0; offset < frame.length; offset += 16) {
  rows.push(`    .db ${[...frame.slice(offset, offset + 16)].map(hex).join(', ')}`);
}

const out = path.join(__dirname, '..', 'src', 'generated', 'qr-frame.inc');
mkdirSync(path.dirname(out), { recursive: true });
writeFileSync(out, [
  `; Generated by tools/generate-demo.mjs — payload: ${payload}`,
  '; 128×64 TI-86 LCD framebuffer, 16 bytes per row, black pixels set to 1.',
  'QR_FRAME:',
  ...rows,
  '',
].join('\n'));

console.log(`[ti86] wrote ${out}`);
console.log(`[ti86] payload=${payload}; Version ${qr.version}, EC M, ${qr.modules.size}×${qr.modules.size} modules at ${SCALE}× scale`);
