#!/bin/sh
# dscli host wrapper — exec into the running daylight-station container.
# Generated by cli/install-host-wrapper.sh; edit there, not here.
exec sudo docker exec -i daylight-station node /usr/src/app/cli/dscli.mjs "$@"
