#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(here, '..', 'include', 'config.h');
const src = process.argv[2] || process.env.DAYLIGHT_PRESSURE_MATS_CONFIG;
if (!src) {
  console.error('ERROR: pass pressure-mats.yml or set DAYLIGHT_PRESSURE_MATS_CONFIG.');
  process.exit(1);
}

const cfg = yaml.load(readFileSync(src, 'utf8')) || {};
// Most household ESP registries carry the same provisioning/backend block.
// A sibling reference keeps those secrets in one place without changing the
// generated header contract. Explicit local values win when present.
const directInheritedPath = cfg.provisioning_from
  ? path.resolve(path.dirname(src), cfg.provisioning_from)
  : null;
// The household data migration nested pressure-mats/config.yml one level below
// shared registries such as scales.yml. Honor the original bare reference while
// deployed data copies converge on the explicit `../scales.yml` spelling.
const migratedInheritedPath = cfg.provisioning_from && !cfg.provisioning_from.includes('/')
  ? path.resolve(path.dirname(src), '..', cfg.provisioning_from)
  : null;
const inheritedPath = [directInheritedPath, migratedInheritedPath]
  .find((candidate) => candidate && existsSync(candidate)) || directInheritedPath;
const inherited = inheritedPath ? (yaml.load(readFileSync(inheritedPath, 'utf8')) || {}) : {};
const provisioning = { ...(inherited.provisioning || {}), ...(cfg.provisioning || {}) };
const backend = { ...(inherited.backend || {}), ...(cfg.backend || {}) };
const mats = cfg.pressure_mats || {};
const id = process.argv[3] || Object.keys(mats)[0];
const mat = mats[id];
if (!mat) {
  console.error(`ERROR: pressure mat "${id}" not found. Available: ${Object.keys(mats).join(', ') || '(none)'}`);
  process.exit(1);
}

const required = {
  'provisioning.wifi_ssid': provisioning.wifi_ssid,
  'provisioning.wifi_password': provisioning.wifi_password,
  'backend.host': backend.host,
  'backend.port': backend.port,
};
const missing = Object.entries(required)
  .filter(([, value]) => value === undefined || value === '')
  .map(([key]) => key);
if (missing.length) {
  console.error(`ERROR: ${src} missing: ${missing.join(', ')}`);
  process.exit(1);
}

const device = mat.device || {};
const detection = mat.detection || {};
const emit = mat.emit || {};
const ota = mat.ota || {};
const otaEnabled = ota.enabled === true;
const otaPassword = String(ota.password ?? '');
if (otaEnabled && !otaPassword) {
  console.error(`ERROR: ${src} (mat=${id}) sets ota.enabled true with no ota.password.`);
  console.error('       An unauthenticated OTA endpoint on the LAN is not an acceptable default.');
  process.exit(1);
}
const number = (value, fallback, min, max, key) => {
  const parsed = Number(value ?? fallback);
  if (!Number.isFinite(parsed) || parsed < min || parsed > max) {
    throw new Error(`${key} must be between ${min} and ${max}; got ${value}`);
  }
  return parsed;
};
const integer = (value, fallback, min, max, key) =>
  Math.round(number(value, fallback, min, max, key));
const esc = (value) => String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const values = {
  sensorPin: integer(device.sensor_pin, 0, 0, 10, 'device.sensor_pin'),
  ledPin: integer(device.status_led_pin, 7, 0, 10, 'device.status_led_pin'),
  pressDelta: number(detection.press_delta_v, 0.12, 0.01, 2.0, 'detection.press_delta_v'),
  pressGradient: number(detection.press_gradient_vps, 0.08, 0.01, 5.0, 'detection.press_gradient_vps'),
  stompDelta: number(detection.stomp_delta_v, 0.48, 0.02, 2.5, 'detection.stomp_delta_v'),
  stompGradient: number(detection.stomp_gradient_vps, 0.20, 0.02, 8.0, 'detection.stomp_gradient_vps'),
  releaseDeltaRatio: number(detection.release_delta_ratio, 0.5, 0.05, 1.0, 'detection.release_delta_ratio'),
  releaseGradientRatio: number(detection.release_gradient_ratio, 0.4, 0.05, 1.0, 'detection.release_gradient_ratio'),
  sampleMs: integer(detection.sample_interval_ms, 50, 20, 1000, 'detection.sample_interval_ms'),
  rawSamples: integer(detection.raw_samples_per_frame, 100, 1, 500, 'detection.raw_samples_per_frame'),
  smoothingFrames: integer(detection.smoothing_frames, 7, 1, 32, 'detection.smoothing_frames'),
  readingMs: integer(emit.reading_interval_ms, 1000, 100, 60000, 'emit.reading_interval_ms'),
  helloMs: integer(emit.hello_interval_ms, 60000, 5000, 3600000, 'emit.hello_interval_ms'),
};

const header = `// GENERATED by tools/gen-config.mjs from ${path.basename(src)} (mat: ${id}) — DO NOT COMMIT.
#pragma once

#define WIFI_SSID                "${esc(provisioning.wifi_ssid)}"
#define WIFI_PASSWORD            "${esc(provisioning.wifi_password)}"
#define WS_HOST                  "${esc(backend.host)}"
#define WS_PORT                  ${integer(backend.port, 3111, 1, 65535, 'backend.port')}
#define WS_PATH                  "${esc(backend.ws_path || '/ws')}"

#define MAT_ID                   "${esc(id)}"
#define SENSOR_PIN               ${values.sensorPin}
#define STATUS_LED_PIN           ${values.ledPin}
#define STATUS_LED_ENABLED       ${device.status_led === false ? 0 : 1}

#define PRESS_DELTA_V            ${values.pressDelta}f
#define PRESS_GRADIENT_VPS       ${values.pressGradient}f
#define STOMP_DELTA_V            ${values.stompDelta}f
#define STOMP_GRADIENT_VPS       ${values.stompGradient}f
#define RELEASE_DELTA_RATIO      ${values.releaseDeltaRatio}f
#define RELEASE_GRADIENT_RATIO   ${values.releaseGradientRatio}f
#define SAMPLE_INTERVAL_MS       ${values.sampleMs}
#define RAW_SAMPLES_PER_FRAME    ${values.rawSamples}
#define SMOOTHING_FRAMES         ${values.smoothingFrames}
#define READING_INTERVAL_MS      ${values.readingMs}
#define HELLO_INTERVAL_MS        ${values.helloMs}

// Authenticated ArduinoOTA (espota invitation on UDP :3232).
#define OTA_ENABLED              ${otaEnabled ? 1 : 0}
#define OTA_PASSWORD             "${esc(otaPassword)}"
`;

writeFileSync(out, header, { mode: 0o600 });
console.log(`[gen-config] ${src} (mat=${id})`);
console.log(`[gen-config] -> ${out}  backend=${backend.host}:${backend.port}${backend.ws_path || '/ws'}  ota=${otaEnabled ? 'on(espota:3232)' : 'off'}`);
