#!/usr/bin/env node
// =============================================================================
// gen-config.mjs — generate firmware include/config.h from the household SSOT
// (data/household/config/scales.yml). Keeps Wi-Fi creds + instance values OUT of
// the repo: the output config.h is gitignored.
//
// Usage:
//   node tools/gen-config.mjs <path-to>/config/scales.yml [scale-id]
//   DAYLIGHT_SCALES_CONFIG=<path> node tools/gen-config.mjs [scale-id]
//
// scale-id defaults to the first key under `scales:`.
// =============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '..', 'include', 'config.h');

const src = process.argv[2] || process.env.DAYLIGHT_SCALES_CONFIG;
if (!src) {
  console.error('ERROR: pass scales.yml path, or set DAYLIGHT_SCALES_CONFIG.');
  process.exit(1);
}

const cfg = yaml.load(readFileSync(src, 'utf8')) || {};
const prov = cfg.provisioning || {};
const backend = cfg.backend || {};
const scales = cfg.scales || {};

const wantId = process.argv[3] || Object.keys(scales)[0];
const scale = scales[wantId];
if (!scale) {
  console.error(`ERROR: scale id "${wantId}" not found. Available: ${Object.keys(scales).join(', ') || '(none)'}`);
  process.exit(1);
}
const ble = scale.ble || {};
const barcode = scale.barcode || {};
const decode = ble.decode || {};
const emit = scale.emit || {};

const need = {
  'provisioning.wifi_ssid': prov.wifi_ssid,
  'provisioning.wifi_password': prov.wifi_password,
  'backend.host': backend.host,
  'backend.port': backend.port,
  [`scales.${wantId}.ble.match_name`]: ble.match_name,
  [`scales.${wantId}.ble.service_uuid`]: ble.service_uuid,
  [`scales.${wantId}.ble.notify_char`]: ble.notify_char,
};
const missing = Object.entries(need).filter(([, v]) => v === undefined || v === '').map(([k]) => k);
if (missing.length) { console.error(`ERROR: ${src} missing: ${missing.join(', ')}`); process.exit(1); }

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const hz = Number(emit.heartbeat_hz) > 0 ? Number(emit.heartbeat_hz) : 0.5;
const heartbeatMs = Math.round(1000 / hz);
const divisor = Number(decode.divisor) > 0 ? Number(decode.divisor) : 1;
const barcodeEnabled = Boolean(barcode.mac || barcode.name);

const h = `// GENERATED by tools/gen-config.mjs from ${path.basename(src)} (scale: ${wantId}) — DO NOT COMMIT.
#pragma once

#define WIFI_SSID          "${esc(prov.wifi_ssid)}"
#define WIFI_PASSWORD      "${esc(prov.wifi_password)}"

#define WS_HOST            "${esc(backend.host)}"
#define WS_PORT            ${parseInt(backend.port, 10)}
#define WS_PATH            "${esc(backend.ws_path || '/ws')}"

#define SCALE_ID           "${esc(wantId)}"
#define SCALE_MATCH_NAME   "${esc(ble.match_name)}"
#define SCALE_SERVICE_UUID "${esc(ble.service_uuid)}"
#define SCALE_NOTIFY_UUID  "${esc(ble.notify_char)}"

#define WEIGHT_OFFSET      ${parseInt(decode.weight_offset ?? 2, 10)}
#define WEIGHT_DIVISOR     ${divisor}
#define STABLE_BYTE        ${parseInt(decode.stable_byte ?? 6, 10)}
#define STABLE_VALUE       ${decode.stable_value != null ? `0x${Number(decode.stable_value).toString(16).toUpperCase()}` : '0xAA'}
#define UNIT_BYTE          ${parseInt(decode.unit_byte ?? 8, 10)}

#define EMIT_MIN_DELTA_G   ${parseInt(emit.min_delta_g ?? 1, 10)}
#define HEARTBEAT_MS       ${heartbeatMs}

#define BARCODE_ENABLED    ${barcodeEnabled ? 1 : 0}
#define BARCODE_ID         "${esc(barcode.id || 'content-barcode')}"
#define BARCODE_ROUTE      "${esc(barcode.route || 'content')}"
#define BARCODE_MAC        "${esc(barcode.mac || '')}"
#define BARCODE_NAME       "${esc(barcode.name || 'DS2278')}"
// Classic-BT name this ESP advertises as the HID *host* — the name the scanner
// shows when pairing. Also the target of the scanner's pairing barcode.
#define BARCODE_HOST_NAME  "${esc(barcode.host_name || 'DaylightScanHost')}"
// 0 = we page the scanner (correct for DS6878: in "Bluetooth Keyboard Emulation
// (HID Slave)" the scanner is the SLAVE and waits for the host to connect —
// DS6878 PRG p.4-5). 1 = stay discoverable and wait for the scanner instead.
#define BARCODE_PASSIVE    ${barcode.passive === true ? 1 : 0}
// Passkey used when io-cap is KeyboardOnly (/barcode/iocap?mode=keyboard). Fixed
// so the operator can pre-stage the digit bar codes instead of racing the SSP
// timeout with a stack-generated passkey.
#define BARCODE_FIXED_PASSKEY ${parseInt(barcode.fixed_passkey ?? 0, 10)}
`;

writeFileSync(OUT, h, { mode: 0o600 });
console.log(`[gen-config] ${src} (scale=${wantId})\n[gen-config] -> ${OUT}  backend=${backend.host}:${backend.port}${backend.ws_path || '/ws'}`);
